-- USO DE LA BASE DE DATOS DE CLEVER CLOUD
USE bia7rex7lojv47f6wwbo;

-- CREANDO TABLAS ENTIDADES FUERTES --
CREATE TABLE tienda (
	id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    ubicacion VARCHAR(255) NOT NULL
);

CREATE TABLE cliente (
	id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    apellido VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);


-- CREANDO TABLAS ENTIDADES DEBILES--

CREATE TABLE producto (
	id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    id_tienda INT NOT NULL,
    CONSTRAINT fk_id_tienda 
    FOREIGN KEY (id_tienda) REFERENCES tienda(id) ON DELETE CASCADE
);


CREATE TABLE compra  (
	id INT PRIMARY KEY AUTO_INCREMENT,
    fecha_compra TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    cantidad INT NOT NULL,
    id_cliente INT NOT NULL,
    id_producto INT NOT NULL,
    CONSTRAINT fk_id_cliente
    FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON DELETE CASCADE,
    CONSTRAINT fk_id_producto
    FOREIGN KEY (id_producto) REFERENCES producto(id) ON DELETE CASCADE
);


-- AGREGANDO LA COLUMNA STOCK EN LA TABLE PRODUCTO --
ALTER TABLE producto
ADD COLUMN stock INT NOT NULL;


-- AGREGANDO REGISTROS DE LAS TIENDAS EN LA TABLA TIENDA -- 
INSERT INTO tienda (nombre, ubicacion) VALUES
("TESORO", "MEDELLIN"),
("TITAN PLAZA", "BOGOTÁ"),
("BUENAVISTA", "BARRANQUILLA"),
("JARDIN PLAZA", "CALI"),
("VIVA", "ARMENIA"),
("LA ESTACION","IBAGUE"),
("CONQUISTADORES","MANIZALES");

SELECT * FROM tienda;



